"""
prepare_corpus.py

Converts all_categories_cot.jsonl (generated by run_all_categories.py)
into a balanced corpus.jsonl ready for train_sft.py.

Steps:
  1. Load all verified CoT records
  2. Optionally cap per-category count to avoid imbalance
  3. Shuffle and write corpus.jsonl

Output: reports/cryptarithm/corpus.jsonl

Usage:
    python scripts/prepare_corpus.py \\
        --input  reports/cryptarithm/all_categories_cot.jsonl \\
        --output reports/cryptarithm/corpus.jsonl \\
        --max_per_cat 1500
"""

from __future__ import annotations

import argparse
import json
import os
import random
from collections import Counter, defaultdict
from pathlib import Path

REPO_ROOT   = Path(__file__).resolve().parent.parent
DEFAULT_IN  = REPO_ROOT / "reports" / "cryptarithm" / "all_categories_cot.jsonl"
DEFAULT_OUT = REPO_ROOT / "reports" / "cryptarithm" / "corpus.jsonl"


def load_jsonl(path: Path):
    records = []
    with path.open(encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if line:
                try:
                    records.append(json.loads(line))
                except json.JSONDecodeError:
                    pass
    return records


def prepare(
    input_path: Path,
    output_path: Path,
    max_per_cat: int,
    seed: int,
) -> None:
    print(f"Loading: {input_path}", flush=True)
    records = load_jsonl(input_path)
    print(f"  Total loaded: {len(records)}", flush=True)

    # Keep only verified records with non-empty CoT
    records = [
        r for r in records
        if r.get("verified") and r.get("cot", "").strip() and r.get("answer", "").strip()
    ]
    print(f"  After verified filter: {len(records)}", flush=True)

    # Group by category
    by_cat: dict = defaultdict(list)
    for r in records:
        by_cat[r.get("category", "unknown")].append(r)

    # Per-category counts before capping
    print("\nCategory distribution (before cap):")
    for cat, recs in sorted(by_cat.items()):
        print(f"  {cat:20s}: {len(recs)}")

    # Cap per category
    rng = random.Random(seed)
    selected = []
    for cat, recs in by_cat.items():
        if len(recs) > max_per_cat:
            recs = rng.sample(recs, max_per_cat)
        selected.extend(recs)

    rng.shuffle(selected)

    print(f"\nAfter cap ({max_per_cat}/cat): {len(selected)} records")
    after_cats = Counter(r.get("category", "unknown") for r in selected)
    for cat, cnt in sorted(after_cats.items()):
        print(f"  {cat:20s}: {cnt}")

    # Write corpus.jsonl — keep fields train_sft.py needs
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w", encoding="utf-8") as fh:
        for r in selected:
            out = {
                "problem_id": r.get("problem_id", ""),
                "category":   r.get("category",   ""),
                "prompt":     r.get("prompt",      r.get("question", "")),
                "answer":     r.get("answer",      ""),
                "cot":        r.get("cot",         ""),
                "rule":       r.get("rule",        ""),
                "verified":   True,
            }
            fh.write(json.dumps(out, ensure_ascii=False) + "\n")


    print(f"\nCorpus written → {output_path}  ({len(selected)} records)", flush=True)


def main() -> None:
    p = argparse.ArgumentParser(description="Prepare balanced training corpus")
    p.add_argument("--input",       default=str(DEFAULT_IN),
                   help="Input JSONL (all_categories_cot.jsonl)")
    p.add_argument("--output",      default=str(DEFAULT_OUT),
                   help="Output corpus.jsonl for train_sft.py")
    p.add_argument("--max_per_cat", type=int, default=1500,
                   help="Max records per category (default: 1500)")
    p.add_argument("--seed",        type=int, default=42)
    args = p.parse_args()

    prepare(Path(args.input), Path(args.output), args.max_per_cat, args.seed)


if __name__ == "__main__":
    main()
